### ISSUE TITLE
change type of dependencies field

### ISSUE THREAD

**Issue by bossie** [Open-EO/openeo-job-registry-elastic-api#31]
Context: https://github.com/Open-EO/openeo-geopyspark-driver/issues/632

The `dependencies` field of the job entity is defined as an array of strings but should be an array of objects instead. Please change it as it is currently blocking a release of OpenEO on Terrascope.

This is an example of what we're trying to PATCH in:

```json
[
  {
    "collection_id": "SENTINEL2_L1C_SENTINELHUB",
    "batch_request_ids": [
      "0f5b0527-1baf-4741-b48b-3d8b00363e29"
    ],
    "results_location": "s3://openeo-sentinelhub/0f5b0527-1baf-4741-b48b-3d8b00363e29",
    "card4l": false
  }
]
```

And this is the error that we currently get back:

```
Traceback (most recent call last):
  File "/opt/venv/lib64/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/venv/lib64/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/opt/venv/lib64/python3.8/site-packages/openeo_driver/users/auth.py", line 88, in decorated
    return f(*args, **kwargs)
  File "/opt/venv/lib64/python3.8/site-packages/openeo_driver/views.py", line 914, in queue_job
    backend_implementation.batch_jobs.start_job(job_id=job_id, user=user)
  File "/opt/venv/lib64/python3.8/site-packages/openeogeotrellis/backend.py", line 2004, in start_job
    self._start_job(job_id, user, _get_vault_token)
  File "/opt/venv/lib64/python3.8/site-packages/openeogeotrellis/backend.py", line 2071, in _start_job
    dbl_registry.set_dependencies(
  File "/opt/venv/lib64/python3.8/site-packages/openeogeotrellis/job_registry.py", line 850, in set_dependencies
    self.elastic_job_registry.set_dependencies(
  File "/opt/venv/lib64/python3.8/site-packages/openeo_driver/jobregistry.py", line 465, in set_dependencies
    return self._update(job_id=job_id, data={"dependencies": dependencies})
  File "/opt/venv/lib64/python3.8/site-packages/openeo_driver/jobregistry.py", line 460, in _update
    return self._do_request("PATCH", f"/jobs/{job_id}", json=data)
  File "/opt/venv/lib64/python3.8/site-packages/openeo_driver/jobregistry.py", line 306, in _do_request
    raise EjrHttpError.from_response(response=response)
openeo_driver.jobregistry.EjrHttpError: EJR API error: 400 'Bad Request' on `PATCH 'https://jobregistry.openeo.vito.be/jobs/j-240121b164094ca6a9070158716c759b'`: {"statusCode":400,"message":["dependencies.0.an unknown value was passed to the validate function"],"error":"Bad Request"}
```

**Comment by JanssenBrm** [comment]
Released new version to the TerraScope production environment.
