### ISSUE TITLE
newly created document not returned in subsequent /jobs/search

### ISSUE THREAD

**Issue by bossie** [Open-EO/openeo-job-registry-elastic-api#32]
Looks like #20 but for POST `/jobs/search`.

Creating and immediately starting an OpenEO batch job frequently fails; the latter tries to fetch the job details from this API but the new job is not returned.

It manifests itself in our CDSE integration tests (`os_creodias_openeo_k8s/kube_resources/applications/integrationtests/tests/test_batch.py`) but regular users are also impacted if they use `create_job` followed by `run_synchronous` or simply `execute_batch`, which are probably the most common patterns. In other words: we can't work around the problem in our tests.

I ran `test_batch.test_s1_sar_backscatter` 10 times in a row and 4 times it failed.

For reference, the stack trace in OpenEO:

```
Traceback (most recent call last):
  File "/opt/openeo/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/openeo/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/opt/openeo/lib/python3.8/site-packages/openeo_driver/users/auth.py", line 88, in decorated
    return f(*args, **kwargs)
  File "/opt/openeo/lib/python3.8/site-packages/openeo_driver/views.py", line 911, in queue_job
    job_info = backend_implementation.batch_jobs.get_job_info(job_id, user.user_id)
  File "/opt/openeo/lib/python3.8/site-packages/openeogeotrellis/backend.py", line 1727, in get_job_info
    job_metadata = registry.get_job_metadata(job_id, user_id)
  File "/opt/openeo/lib/python3.8/site-packages/openeogeotrellis/job_registry.py", line 811, in get_job_metadata
    self._check_zk_ejr_job_info(job_id=job_id, zk_job_info=zk_job_info, ejr_job_info=ejr_job_info)
  File "/opt/openeo/lib/python3.8/site-packages/openeogeotrellis/job_registry.py", line 824, in _check_zk_ejr_job_info
    raise JobNotFoundException(job_id=job_id)
openeo_driver.errors.JobNotFoundException: The batch job 'j-240122b2020e4015a5da65e4765960fa' does not exist.
```

**Comment by JanssenBrm** [comment]
@bossie  - Can you test the latest release with v1.19.2? We've moved the retry mechanism to a lower level to ensure all job-related queries are retried 5 times (with 500ms) in between before sending empty results.

As with the `PATCH` request, this is mainly caused by ES taking a couple of ms to propagate the new data amongst its shards. Querying directly after storing could in that case mean that no result could be found.

**Comment by bossie** [comment]
I figured it had to do with eventual consistency. Will try it out :+1:

**Comment by bossie** [comment]
20 tests, all green. :muscle:
